### ISSUE TITLE
let page sync LAN multi-devices when file changed

### ISSUE THREAD

**Issue by lichnow** [JeffreyWay/laravel-mix#1071]
Because webpack dev-server and hmr cannot sync LAN multi-devices to hot replace,so if I want to sync LAN multi-devices,I must use `npm run watch` instead `npm run hot` and let `browserSync` reload is true,so please change reload of browsersync `false` to !Mix.isUsing('hmr').
```
if (Mix.isUsing('browserSync')) {
        let BrowserSyncPlugin = require('browser-sync-webpack-plugin');

        plugins.push(
            new BrowserSyncPlugin(
                Object.assign({
                    host: 'localhost',
                    port: 3000,
                    proxy: 'app.dev',
                    files: [
                        'app/**/*.php',
                        'resources/views/**/*.php',
                        'public/js/**/*.js',
                        'public/css/**/*.css'
                    ]
                }, Config.browserSync),

               // change false to :!Mix.isUsing('hmr')
                { reload:!Mix.isUsing('hmr')}
            )
        );
    }

```

**Comment by marchershey** [comment]
Bringing this old issue out of the grave, because it's the top result when searching for "_larvel hmr on local network_".

I found a fix for this. 

In your `webpack.mix.js` file, add the following to the bottom:

```js
// To allow HMR to work on devices on the local network,
// the following config and options need to be set.

// This sets your `mix()` assets to `http://localhost:8000` (to work with `php artisan serve`)
mix.webpackConfig({
    devServer: {
        proxy: {
            '*': 'http://localhost:8000'
        }
    },
})

// This sets your HMR host and port to the device running `php artisan serve`
mix.options({
    hmrOptions: {
        host: '10.0.0.31', // set this to the local ip address (192.168.0.**) of whatever device is running `php artisan serve`
        port: 8000 // set this to which port `php artisan serve` is using.
    }
})
```

After you have added the above to your `webpack.mix.js` file...

1. In one tab, run `php artisan serve`
2. Then on another tab, run `npm run hot`

🎉 Hot reloading should now work perfectly on devices on your local network! 🎉 

**Note:** There may be a better way to do this. I am in no way an expert, but after digging around for several hours, this is what I found works best for me.
