### ISSUE TITLE
Mix extract doesnt play nice with shared workers

### ISSUE THREAD

**Issue by karljakober** [JeffreyWay/laravel-mix#1111]
- Laravel Mix Version: 1.4.2
- Node Version (`node -v`): 6.4.0
- NPM Version (`npm -v`): 4.5.0
- OS: Ubuntu 16.04 64bit

### Description:
I use a shared worker in our program, and if mix extract is used anywhere within the mix config, it causes webpackjsonP not defined errors in the shared worker itself.

I figured putting the shared worker in a seperate mix block would cause the vendor to not be extracted for this file, but apparently that is not how mix handles this. https://github.com/KarlJakober/mix-test/blob/master/webpack.mix.js#L6

Im looking for a way to exclude this file specifically from extract so all vendors are bundled properly

### Steps To Reproduce:
Clone the following: https://github.com/KarlJakober/mix-test
`npm install`
`npm run dev`
`node app.js`
if you navigate to localhost:8080 and go to chrome://inspect -> shared workers tab -> inspect (in chrome obviously) you will receive the following
![screenshot from 2017-08-11 12-38-52](https://user-images.githubusercontent.com/140006/29229511-aeceacb2-7e93-11e7-8f75-d84e80ee4baf.png)

Edit: just wanted to add to this, even prepending the manifest.js to the worker will not work as there is no window in a shared worker

**Comment by jjhesk** [comment]
@karljakober same problem here

**Comment by dotnetCarpenter** [comment]
@karljakober I had the same issue and it took a long while to track it down. As I see it, it's not possible to use extract, since all webpack module loading is now in the `manifest.js` file which then needs to be in the same browser context as every other file.

If you do not use `extract` then webpack module loading will be duplicated in each file you output to via `mix.js`. Then it works but is not as optimal for your app, since you will have to invalidate the entire app every time, either a vendor is updated or you app code is updated.

It doesn't matter to laravel-mix, if you chain method calls or put them each on a seperate lines.

I think the best work-around is to have multiple _webpack.mix.js_ files. One for your main app, and one for each standalone file that needs to be a webworker, sharedworker or in my edge-case; a standalone file that needs to be injected into a third party iframe.

**Comment by dotnetCarpenter** [comment]
Or use `mix.copy()` if you do not need to transpile the code in your shared worker.
