### ISSUE TITLE
Asset folder  is not flatted with copy() after run prod/dev

### ISSUE THREAD

**Issue by mts88** [JeffreyWay/laravel-mix#1175]
- Laravel Mix Version: 1.4.2 (`npm list --depth=0`)
- Node Version (`node -v`): v6.11.1
- NPM Version (`npm -v`): 3.10.10
- OS: MacOSX 10.12.6

### Description:
When I launch npm run dev o npm run prod, asset/plugins folder (and the others folders in webpack.mix.js) is replaced with a copy not flatted of structure, even if command is copy() and not copyDirectory()

### Steps To Reproduce:
npm run dev / npm run prod

**Comment by Olian04** [comment]
@CicciMTS  `copy()` and `copyDirectory()` does the same thing when targeting a folder.

**Comment by CicciMTS** [comment]
From Laravel Docs seems that `copy()` copy folders content in flatten structure, instead `copyDirectory()` copy folders maintains the original structure.

**Comment by Olian04** [comment]
@CicciMTS  The [documentations on `copy`](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/copying-files.md) doesn't say anything about keeping or flattening structures.
> From time to time, you'll want to copy one or more files, as part of your build process. No problem; that's a cinch. Use the mix.copy() method to specify the source file or folder, and then your desired destination.

**Comment by CicciMTS** [comment]
Sorry, I'm talking about Laravel Docs [Copying Files & Directories](https://laravel.com/docs/5.5/mix#copying-files-and-directories), my bad.
I'm insisting because in other pc (also Mac OSX 10.12.6), copy seems works like Laravel Docs. And, looking in laravel-mix changes, function `copy()`, have internal parameter `flatten=true`.
[Commit-206c14a](https://github.com/JeffreyWay/laravel-mix/commit/206c14a3afa25e70b437cf8e7121bafa054e1307)

Are you really sure?

**Comment by devcircus** [comment]
To clarify, that page from the Laravel docs is referring to the mix specific copy and copyDirectory commands.

**Comment by CicciMTS** [comment]
How can i copy folder content in flatten structure? Wildcard?
