### ISSUE TITLE
Avoid loading JavaScript maps

### ISSUE THREAD

**Issue by tillkruss** [JeffreyWay/laravel-mix#1190]
- Laravel Mix Version: 1.4.3
- Node Version: 8.4.0
- NPM Version: 5.4.1
- OS: macOS 10.12.6

### Description:

I'm importing Popper.js like this: 

```js
import Popper from 'popper.js';
window.Popper = Popper;
```

And it works perfectly, but in my Browser console I see the following error message:

```
https://example.com/js/popper.js.map: Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404)
```

Is there any way to strip all source map references in JavaScript files?

**Comment by ankurk91** [comment]
I don't think it is Laravel mix fault.
Popper.js npm package comes with sourcemap files, (screenshot)
![screenshot from 2017-09-17 10-01-41](https://user-images.githubusercontent.com/6111524/30518016-6a6a92ac-9b8f-11e7-97ff-0d5ac78e1869.png)

The `umd/popper.js` file has a link to these sourcemap files, see next source code
https://unpkg.com/popper.js@1.12.5/dist/umd/popper.js
When you open up devtools, chrome tries to download these linked map files but could not, because these files are in `node_modules` (behind your public folder).

FYI: Chrome will not download source map file unless you open dev tools.

**Comment by FezVrasta** [comment]
Popper.js provides the maps, so it's not its fault if they don't get served by Laravel

**Comment by tillkruss** [comment]
It's actually Safari that tries to download it, not Chrome.

Is there an easy way to strip comments containing `sourceMappingURL` with Mix?

**Comment by jeroendesloovere** [comment]
The following code solved it for me:
```
import { Popper } from 'popper.js'
window.Popper = Popper
```
> I have added `{}` brackets around Popper
