### ISSUE TITLE
vue-template-compiler@2.4.4 incompatible with vue@2.5.0

### ISSUE THREAD

**Issue by sebastiansulinski** [JeffreyWay/laravel-mix#1263]
I've just installed a new `vue@2.5.0`, but unfortunately it is not compatible with `vue-template-compiler@2.4.4` - could you please update this dependency?

**Comment by apocalyarts** [comment]
I have the same problem, only inversed. I just made some package updates and I need vue 2.4.4 because of some dependencies. Now Laravel Mix always defaults to 2.5.0 of the vue-templat-compiler.

The vue-loader is designed so that it is always possible to specify explicit versions for vue and the vue-template-compiler. Laravel Mix does currently not respect this design approach.

I think Jeffrey needs to fix the package.jon like this:

```
"peerDependencies": {
    "vue-template-compiler": "^2.0.0"
  },
```

**Comment by artemsky** [comment]
maybe you just should install it `npm install vue-template-compiler@latest`

**Comment by ctf0** [comment]
@JeffreyWay everytime vue gets updates so does vue-template-compiler , which require to remove and readd laravel-mix everytime , is there a way to fix/prevent this ?

**Comment by lukepolo** [comment]
you can just reference the dependency yourself to override it
