### ISSUE TITLE
Can't copy files to the right folder when setting a different public path.

### ISSUE THREAD

**Issue by luukhoeben** [JeffreyWay/laravel-mix#1272]
- Laravel Mix Version: 1.5.0
- Node Version (`node -v`): 8.1.2
- NPM Version (`npm -v`): 5.5.1
- OS: MacOS High Sierra

### Description:
The company I work for has a styleguide folder in which they compile all of the necessary files. It is in raw gulp still and I want to convert it to laravel mix because the API is so much more fluent. The problem I'm facing is this: I have to convert a file and put it in the public folder (which works great), but then I have to copy that file to the styleguide folder for some sort of local documentation we have. So I've made this:

```
styleguide
- src
- dist
public
- js
- css
```

I've used the setPublicPath function to set the mix public path to `../` (the root of the project, since mix is in the styleguide folder). when I compile to the `public/js/app.min.js` it works, but then when I try to copy this file to the `styleguide/dist/js/app.min.js` that's where it gets weird to me.. It just makes a folder called `dist` in the root and ignores the styleguide folder.

### Steps to reproduce:

create a folder called `styleguide`, install mix in that folder, create a folder called `src` and put all of the files you want to compile in there. then run mix with a config like this:

```js
mix.setPublicPath('../');

mix.js([
    'node_modules/vue/dist/vue.js',
    'src/assets/toolkit/scripts/app.js'
], 'public/js/app.min.js')
.copy('public/js/app.min.js', 'styleguide/dist/js/app.min.js');
```

Is this a bug or am I just doing something wrong?

- Luuk

**Comment by luukhoeben** [comment]
Well, I've made some progress but it's still weird.

This works and outputs to the right folders but some weird things are happening:
```js
let mix = require('laravel-mix').setPublicPath('../'); // project root

mix.js([
    'node_modules/vue/dist/vue.js', // relative to root/styleguide folder
    'src/assets/toolkit/scripts/vue.js' // relative to root/styleguide folder
], 'public/js/vue.min.js') // relative to root folder
.copy('../public/js/vue.min.js', 'dist/js/vue.min.js'); // relative to root/styleguide folder.
```

Is there a reason that it seems so inconsistent?

**Comment by alanondra** [comment]
I'm also running into issues:

	mix.setPublicPath('public/build');

	mix.sass('resources/assets/sass/app.scss', 'public/css')
		.js('resources/assets/js/app.js', 'public/js');

	mix.copy('public/build/mix-manifest.json', 'public/mix-manifest.json');

	mix.version();

It builds the CSS file to `public/build/public/css/app.css` and the JS file to `public/build/public/build/public/js.app.js`.

The method `mix.copy` presents a moving target for each parameter, with the working directory wildly and flippantly changing with each new attempt at changing the parameters. Sometimes it uses the application's base directory, sometimes it works inside the configured public directory, sometimes it works inside the default public directory regardless of settings. Whenever you insert a new parameter to work with the last working directory you were looking at, it changes to a different working directory so that your call fails. It does this 100% of the time.

I think there are two issues:

1. The working directories need to be more firmly established.
2. There should be an additional `setBuildPath` (where the underlying property defaults to `null`) for instances where someone wants to keep their built resources in one tidy location, instead of scattering them about, making it more of a fuss to maintain in any working repository.

**Comment by luukhoeben** [comment]
the `mix.js()` function doesn't seem to work properly, the `mix.scripts()` function seems to do. though I'm having trouble with the copy function still.. if I set this as the output path: `dist/js/app.min.js` it creates the right file in the right folder (`styleguide/dist/js/app.min.js`) but then the mix-manifest.json says `/dist/js/app.min.js` instead of `styleguide/dist/js/app.min.js`.

**Comment by luukhoeben** [comment]
Now a few days later and I have tried some things but haven't got it to work, I still don't know if I'm just doing something wrong or something with the path's is messed up.. anybody had this problem and knows how to fix it? I'll look in the source tonight aswell.

**Comment by sajaddp** [comment]
@luukhoeben,
 Have you finally managed to fix this problem?

**Comment by luukhoeben** [comment]
@sajaddp hey, no I just restructured my folder haha.

**Comment by alanondra** [comment]
Look at the variable `mix.config.fileLoaderDirs` and see if modifying it's properties in your `webpack.mix.js` file helps.
