### ISSUE TITLE
down due to deprecation of gulp-utils@3.0.8

### ISSUE THREAD

**Issue by moeen-basra** [JeffreyWay/laravel-mix#1395]
- Laravel Mix Version: *
- Node Version (`node -9.3`): 
- NPM Version (`npm -5.6`): 
- OS: Debian

### Description:
Hi Jeffrey, all versions of larave-mix are broken due to the deprecation of gulp-utils@3.0.8
here is the dependency tree that I come to know with laravel-mix
laravel-mix > img-loader > imagemin-gifsicle > gifsicle > bin-build > download > gulp-decompress > gulp-util@3.0.8

### Steps To Reproduce:
Here is the article by the author regarding the fix https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by ankurk91** [comment]
Laravel mix is using latest version of `img-loader`; what else we can do?

Someone has already raised similar issue, see
https://github.com/imagemin/gifsicle-bin/issues/78
The package `gifsicle` is still using `bin-build` v2 while this issue was fixed in `bin-build` v3.x.
`bin-build` v3 was released on Jun 17, 2017.

BTW, deprecation does not mean broken, npm will show a warning when installing [deprecated](https://docs.npmjs.com/cli/deprecate) package.
When you says `broken`, do you see any error during build process ?

**Comment by moeen-basra** [comment]
It was not compiling yesterday but today I just tried again and its compiled with a deprecation notice.
Thanks @ankurk91

**Comment by chriz74x** [comment]
shouldn't this be addressed by the author of gulp-decompress?

**Comment by billdanbury** [comment]
Should this issue be reopened and renamed to indicate the NPM Deprecation of deep-dependent gulp-util@3.0.8 via imagemin-gifsicle@5.2.0 and gulp-decompress@1.2.0 ? 

There is a PR for gulp-decompress which is code-complete, but still pending deployment...
https://github.com/kevva/gulp-decompress/pull/13

**Comment by IamAnotherOne** [comment]
Same problem here, failed `npm install` on fresh installed Laravel :
```
npm ERR! gifsicle@3.0.4 postinstall: `node lib/install.js`
npm ERR! Exit status 1
```
Windows 7 64bit
node v8.9.4
npm 5.6.0

**Comment by MatteoMeil** [comment]
I solved downgrading node.js version to 7.10.0

Using version 9.7.1 resulted in EINTEGRITY and other errors.
Don't know if this answer is redundant, but I didn't see the solution so posted a comment for others that will come in this thread
