### ISSUE TITLE
Question: [BABEL] Note: The code generator has deoptimised

### ISSUE THREAD

**Issue by marcelogarbin** [JeffreyWay/laravel-mix#1414]
- Laravel Mix Version: 1.7.2
- Node Version (`node -v`):  8.9.4
- NPM Version (`npm -v`): 5.6.0
- OS: Win10 64b

### Description:
I have several scripts to merge into a single file. I was using "mix.scripts()", but when running in production mode I got feedback that it would be better to use "mix.babel()", perhaps because of the amount of scripts I use. I made the exchange, it works correctly, but I always get the message below.

> [BABEL] Note: The code generator has deoptimised the styling of "unknown" as it exceeds the max of "500KB".

Should I care?

### Steps To Reproduce:
- npm run prod

Thank's

**Comment by ankurk91** [comment]
Laravel mix suggests you to use `mix.babel()` when `uglify-js` failed to compress a ES6 syntaxed js file.
There is no harm using `mix.babel()`.

mix.babel() = babel + uglify-js

**Comment by marcelogarbin** [comment]
Ok, that's what I'd like to know. If it is not damaged then it's all right. thank you

**Comment by BobLisa** [comment]
I had to seen this issue,and as this error:The code generator has deoptimised the styling of "xxx/xxx/templates.js  as it exceeds the max of 500KB " when a templates.js document was packaged for webpack.So I found some method to resolve it.  I know a  truthful thing Because we could use the different program frames.
You can find gulpfile.js and search the word "babelify", exmaple :

bundler.transform("babelify", { "compact": false,presets: ["es2015"] }); 

you can see above setting ,I only added "compact":false, Hope to help you.
