### ISSUE TITLE
Mix Copy does not copy _file correctly

### ISSUE THREAD

**Issue by minthemiddle** [JeffreyWay/laravel-mix#1450]
### Version
- laravel-mix@1.7.2
- npm: 5.6.0 

### Description:
Mix does not copy `_files` correctly. It creates another subfolder. This prevents Mix creating for example redirect files for Netlify.

### Expected
`mix.copy('./redirects.txt', './test/_redirects');`
`./test/_redirects` exists

### Instead
`./test/_redirects/redirects.txt`

**Comment by devcircus** [comment]
with that command, you're telling mix to take your 'redirects.txt' file and place it in './test/_redirects'. Which looks like that is exactly what happened.  If you just want the file copied, not in a subfolder, just specify the file extension.
```mix.copy('./redirects.txt', './test/_redirects.txt');```
Otherwise, it will place the file in ```'./test/_redirects'```

**Comment by minthemiddle** [comment]
The problem is: `_redirects` does not have an file extension as per [Netlify's documentation](https://www.netlify.com/docs/redirects/). I use a workaround: `cp _redirects` after Mix.

**Comment by tpraxl** [comment]
Did you try to rename `./redirects.txt` to `./_redirects` in the first place and use `mix.copy('./_redirects', './test/_redirects');`? If that creates a subfolder, it might possibly be considered a bug. If not, then the problem is simply that your call can be interpreted in two ways and mix decides to go for a folder.

**Comment by devcircus** [comment]
Ahh interesting.
