### ISSUE TITLE
minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

### ISSUE THREAD

**Issue by RobWJacob** [JeffreyWay/laravel-mix#146]
can someone help me to solve this?
i am on windows 10, npm v3.10.8, node v6.9.1

```
`-- laravel-mix@0.5.3
  +-- babel-core@6.21.0
  | `-- minimatch@3.0.3
  `-- concatenate@0.0.1
    `-- globs@0.1.2 (git://github.com/stephenmathieson/node-globs.git#80bb9161c8c178f8836fff34da3afd1cbc87cedb)
      `-- glob@4.5.3
        `-- minimatch@2.0.10
```

**Comment by QWp6t** [comment]
It's safe to ignore since it's only a warning and you're only using it during development..

This is caused by [`concatenate`](https://github.com/JeffreyWay/laravel-mix/blob/master/package.json#L27) using [`globs`](https://github.com/stephenmathieson/node-concatenate/blob/master/package.json#L12) which uses old version of [`glob`](https://github.com/stephenmathieson/node-globs/blob/master/package.json#L11) which uses old version of [`minimatch`](https://github.com/isaacs/node-glob/blob/v4.5.3/package.json#L22).

Submitting PR to [globs repo](https://github.com/stephenmathieson/node-globs) updating the version of `glob` would resolve this upstream issue.
