### ISSUE TITLE
Unable to use Hot Replace with Vagrant Environment

### ISSUE THREAD

**Issue by darorl89** [JeffreyWay/laravel-mix#1494]
Hey. While using Vagrant as a server, I'm unable to use hot replace because mix is not allowing to set the public address, and assumes it's localhost:8080 instead. Vagrant on Windows/HyperV does not allow to forward ports, hence I need to point local ip instead of localhost here. Looking forward for a fix.

**Comment by ankurk91** [comment]
Since laravel mix v2.x, it allows you to configure port

https://github.com/JeffreyWay/laravel-mix/pull/1246

**Comment by patrick-hertling** [comment]
Im having the same issue.
I don't know if it is because "mix is not allowing to set the public address". I can access the js file on `localhost:8080/js/app.js`. If I use the `mix(...)` function and load the page over its virtual host(lets say app.test), the page loads and everything is good.

BUT: When I change something, after the javascript recompiles, `localhost:8080/js/app.js` still gives me the exact same content. Its not getting updated after the recompile. Even if I refresh the page with F5, the bundle remains the exact same... Any ideas?

@ikudosi 's solution didn't help me neighter unfortunatly.

**Comment by patrick-hertling** [comment]
I got it to work litery just folloring this:
https://github.com/JeffreyWay/laravel-mix/issues/1483#issuecomment-366685986

**Comment by jlsjonas** [comment]
> I got it to work litery just following this instructions:
> [#1483 (comment)](https://github.com/JeffreyWay/laravel-mix/issues/1483#issuecomment-366685986)

Looks like this solution no longer works with laravel-mix ^3.0.0 (neither directly in windows via Laragon, nor via homestead)

When including it, I get server the files on _initial hot_ but changes are not pushed
When leaving it out, the _connection_ is there (to push updates), but the files are incorrect (resulting in a blank site).

Anyone experiencing a similar issue?
