### ISSUE TITLE
Laravel mix not compiling vue components

### ISSUE THREAD

**Issue by TomMorison12** [JeffreyWay/laravel-mix#1660]
- Laravel Mix Version: 5.4.* (`npm list --depth=0`)
- Node Version 8.11.1 (`node -v`): 
- NPM Version 6.0.0 (`npm -v`): 
- OS: 

### Description:
I had an old project that used Laravel 5.3 and I recently upgraded it to Laravel 5.4 I updated my composer.json file to get Laravel 5.4, and I followed the upgrade guided for 5.4 Then, I created a package.json file and npm install. My node modules were installed. Next, I run npm run dev, and the JavaScript compiles, however, the Vue component which I am sure I have mounted never gets compiled.

I have created a fresh install of Laravel and tried compiling the component, and it works. However, I need the component to work in my old project. Were there ny steps I missed when installing mix? 
### Steps To Reproduce:
1. Update from Laravel 5.3 to 5.4
2. Create package.json file
3 run npm install 
4. run npm run dev

**Comment by FrancoisH** [comment]
Just my two cent here but, could you check if you're using vue-loader 15.x or vue-loader 14.x currently?

It seems vue-loader 15.x is not handled yet by laravel mix, at least you have to manually tweak the config.

Kind regards.

**Comment by JeffreyWay** [comment]
If someone can give me reproducible steps, I’ll take a look. But I can’t reproduce this on my end.

**Comment by joaomnb** [comment]
I bumped into the same issue. I fixed it by adding `.default` when requiring single file components, according to recent changes in Laravel: https://github.com/laravel/laravel/blob/master/resources/js/app.js

Example:
```javascript
Vue.component('example-component', require('./components/ExampleComponent.vue'));
```
becomes
```javascript
Vue.component('example-component', require('./components/ExampleComponent.vue').default);
```

**Comment by Wells4sure** [comment]
Found the same issue today and @joaomnb  **.default** Fixed it thanks

**Comment by j3rg** [comment]
@joaomnb thank you so much this helped me resolved my issue. I want to learn why the `.default` fixed it. Can you point me in the direction of learning the inner workings?

Thanks in advance

**Comment by joaomnb** [comment]
Hi @j3rg, sure. This is due to vue-loader moving from the older CommonJS module syntax, `module.exports = {...}`, to the newer ES6 module syntax `export default {...}`.

So, the error was caused because we were now attempting to import an ES6 module using the `require()` method, which is CommonJS syntax. There are (at least) two ways of fixing the code:

The one I posted above, changing `require(...)` to `require(...).default` – which is kind of a "hack", since we are now mixing the two syntaxes.

And a probably better solution, that I hadn't understood yet when I posted, which is adopting the ES6 way of importing modules... So this:
```javascript
Vue.component('example-component', require('./components/ExampleComponent.vue'));
```
becomes this:
```javascript
import ExampleComponent from './components/ExampleComponent.vue';
Vue.component('example-component', ExampleComponent);
```

I hope that is clear enough! 😄
