### ISSUE TITLE
Doesn't work with Magento 1.x

### ISSUE THREAD

**Issue by xbold** [JeffreyWay/laravel-mix#1686]
- Laravel Mix Version: 2.1.11
- Node Version (`node -v`): 8.10.0
- NPM Version (`npm -v`): 3.5.2
- OS: Ubuntu 18.04

### Description:
Laravel Mix installs fine, compiles assets fine, but browsersync is a no go. It opens the site in localhost:3000 and even compiles when assets change, but never actually injects style changes. I have to refresh the page to see any stylesheet changes.

We normally use gulp for this, but since we're using Laravel Mix now in our Laravel (obviously) and our Wordpress builds, we wanted to make it universal and use it for our Magento sites.

### Steps To Reproduce:
Install a new Magento 1.x site in Homestead.
Run `yarn add laravel-mix --dev`
Copy over config file and point it to assets / set up browsersync
Run npm run watch or yarn watch
Change a stylesheet
Watch it do nothing

**Comment by viktorbijlenga** [comment]
I would suggest trying something like this:
````js
mix.browserSync({
    proxy: 'domain.tld',
    files: [
        "path/css/*.css", 
        "path/js/*.js", 
        "*.php"
    ]
 });
````

**Comment by octoxan** [comment]
@viktorbijlenga This did it!

**Comment by octoxan** [comment]
@viktorbijlenga 
How would you do this with just "any file in this folder"

I tried adding https://github.com/ctf0/laravel-mix-versionhash because the way Mix versions by default doesn't work for us. It creates files like style.45342.css and this breaks browsersync again.

I have tried this...

```js
.browserSync({
        proxy: 'bosu.test',
        files: [
            'skin/frontend/theme/default/dist/*',
        ]
    });
```

as well as `**/*.css` and it just doesn't inject changes anymore, until I go back to regular versioning.

**Comment by krimo** [comment]
This is still an issue, I have to manually reload to see any change
