### ISSUE TITLE
Document setPublicPath and setResourceRoot

### ISSUE THREAD

**Issue by 75th** [JeffreyWay/laravel-mix#2034]
I was trying to get a slightly unusual file output setup working, and I didn't fully understand these two methods. In the official docs, setPublicPath is only mentioned twice, both times in examples without a thorough explanation of what it does, and setResourceRoot isn't mentioned at all.

It took me an hour of trial and error before I understood those functions (and their effects on CSS and other mix methods) well enough to configure my project correctly. It would be nice to have an official explanation in an easily-findable place in the official documentation.

**Comment by cjd118** [comment]
I found this link in Google because I was struggling to work out the differences between `setPublicPath` and `setResourcePath`. Please document these. 

For anyone else:

`setPublicPath` sets the base output path for any mix assets. Fonts, images etc.

`setResourcePath` sets the base output path in the generated assets relative to the public root (e.g. url('/css/fonts/font.tty'));

```
mix.setPublicPath('public_html/css');
mix.setResourceRoot('/css');
```

**Comment by nickwelsh1** [comment]
This documentation is still required. I think these two settings may be even more necessary for Windows users.

**Comment by nickwelsh1** [comment]
setResourceRoot is not mentioned anywhere on laravel-mix.com
I think this would be very valuable to add to the docs
