### ISSUE TITLE
Laravel Mix extract all vue component css to single app.css

### ISSUE THREAD

**Issue by essivision** [JeffreyWay/laravel-mix#2139]
-   Laravel Mix Version: 4.0.16 
-   Node Version : 10.15.2
-   NPM Version : 6.4.1
-   OS: Windows 10

### Description:
I use `Laravel Mix` to compile and extract component css to single file such as `app.css`. For example I have a component like this:
```vuejs
<template>
   <div class="text">  </div>
<template>
 ...
<style>
   .text{ color: red; }
</style>
``` 

In `webpack.mix.js` is:
```javascript

mix.autoload({
    jquery: ['$', 'window.jQuery','window.$'],
    quill: ['window.Quill','Quill']
});

mix.options({
    extractVueStyles: 'public/css/app.css',
});

mix.js('resources/assets/js/app.js', 'public/js')
    .sourceMaps()
    .version();
```

and I put this code in `master..blade.php`
```php
    <link rel="stylesheet" href="{{ url(mix('/css/app.css')) }}">
```

But `app.css` is **empty** and my component css put in `html>head` as inline style:
```html
<html>
<head>
   ...
   <style>
         .text{ color: red; }
   </style>
</head>
...
</html>
```

What should I do to extract and put all component css in `app.css`?

**Comment by monkeymonk** [comment]
Same here, using `extractVueStyles` just do nothing. Any clues ?

**Comment by lorenzowoodridge** [comment]
I'm having the same issue as well.

**Comment by iwasherefirst2** [comment]
I just tried a fresh install and it seems to as expected. Of course, after making changes to `webpack.mix.js` you need to call `npm run dev` or `npm run prod` or restart the watch command so that the changes have effect.

Here some examples that worked for me:

Example 1: Put css from components in file `vue-components.css` 
```
mix.options({
  extractVueStyles: 'public/css/vue-components.css'
});

mix.js('resources/js/app.js', 'public/js');
```

Example 2: Put css from components in file `vue-components.css` and compile `app.scss` into `app.css`
```
mix.options({
  extractVueStyles: 'public/css/vue-components.css'
});

mix.js('resources/js/app.js', 'public/js')
 .sass('resources/sass/app.scss', 'public/css');
```


Example 3: Put css from components into `app.css` and compile `app.scss` into `app.css`
```
mix.options({
  extractVueStyles: true
});

mix.js('resources/js/app.js', 'public/js')
 .sass('resources/sass/app.scss', 'public/css');
```

**Comment by Tofandel** [comment]
If I have multiple entrypoints, is there any way to get the extracted vue styles to be separated based on the entrypoint and not have one big css file with all the css of all the components?
