### ISSUE TITLE
build empty css when using .js and .react together

### ISSUE THREAD

**Issue by sergey-yabloncev** [JeffreyWay/laravel-mix#2147]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`) 4.0.16
-   Node Version (`node -v`):11.15.0
-   NPM Version (`npm -v`): 6.9.0
-   OS: linux Manjaro 

### Description:

build empty css when using .js and .react together

### Steps To Reproduce:

build empty css

mix.react('resources/js/admin/app.js', 'public/js/admin')
.js('resources/js/web/app.js', 'public/js/web')
.sass('resources/sass/web/app.scss', 'public/css/web');

if you comment out .react or .js with sss build correctly

mix.react('resources/js/admin/app.js', 'public/js/admin')
//.js('resources/js/web/app.js', 'public/js/web')
.sass('resources/sass/web/app.scss', 'public/css/web');

or
mix.js('resources/js/web/app.js', 'public/js/web')
.sass('resources/sass/web/app.scss', 'public/css/web');

**Comment by carlmagumpara** [comment]
same here

**Comment by rbcunhadesign** [comment]
I'm having the same problem.. It started out of nowhere.

I've tried removing the node_modules folder and running `npm install` and still spits out an empty css file.

**Comment by skeeith** [comment]
I have the same issue when I use VueJS.

the .extract([vue]) on my config is messing it up.

**Comment by enghelewa** [comment]
As by @JeffreyWay https://github.com/JeffreyWay/laravel-mix/issues/2123#issuecomment-500421264 This is because of dynamic imports problem. And till the new webpack released , there is a temporary workaround for this problem by making a separate mix files for js and scss.
Please refere to this comment posted by @vesaka in https://github.com/JeffreyWay/laravel-mix/issues/1914#issuecomment-503392761

**Comment by sergey-yabloncev** [comment]
actual problem
