### ISSUE TITLE
Problem with SASS, when using url()

### ISSUE THREAD

**Issue by Landish** [JeffreyWay/laravel-mix#218]
Current directory structure and files:

```
resources/assets/sass/app.scss
resources/assets/sass/images/bg.jpg
```

`app.scss` contains:

```css
body {
  background: white url('../images/bg.jpg');
}
```

`webpack.mix.js` file contains:

```js
mix.copy('resources/assets/images', 'public/images');
mix.sass('resources/assets/sass/app.scss', 'public/css');
```

after running `npm run dev` command, the result is:
```
public/css/app.css (correct)
public/images/bg.jpg (correct)
public/bg.jpg (incorrect)
```

`sass` adds/copies all the images specified in `.scss` files with `url()` to the `public` dir.

P.S. The problem seems to be only with images. I'm using custom web fonts, which i'm serving locally and it does not copy .woff files to the public dir.

**Comment by JeffreyWay** [comment]
That's because Webpack will automatically move the images over for you. Up until this morning, the images were being dumped in the public/ directory, but I just made a commit that will place them in public/images instead. 

So, once I tag this (and once you update), you can remove the mix.copy() section entirely.
