### ISSUE TITLE
[Proposal] use webpack-merge to merge webpack configs when using the .webpackConfig method

### ISSUE THREAD

**Issue by SethTompkins** [JeffreyWay/laravel-mix#220]
Link to the project: https://github.com/survivejs/webpack-merge

The package provides smart merging features for combining multiple webpack configs. I may have some time today or tomorrow to whip up a PR and make some examples.

**Comment by QWp6t** [comment]
I was going to suggest this the other day, but when looking at the code, it seems that jway is [already doing something similar using `_.mergeWith()`](https://github.com/JeffreyWay/laravel-mix/blob/8bb844/src/Mix.js#L62-L74), a technique that could be done in the `webpackConfig()` method itself.

the only added benefit over that would be `merge.strategy()` and `merge.smart()` offered by `webpack-merge`, so if implemented in `laravel-mix`, the api should somehow expose those functions, otherwise it's no different from what jway is already doing.

**Comment by JeffreyWay** [comment]
Yeah, unless there's a very specific benefit (give me a use case) to using webpack-merge, I think we'll just stick with the implementation I have.
