### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by JosuelRocha** [JeffreyWay/laravel-mix#2262]
Why doesn't Laravel-mix adopt versioning in the filename ([name].[hash:8].[ext]) instead of query string? Query versioning is problematic, has problems with CDN, caching, proxy etc, and does not look good.

So much so that it was necessary to create an extension as an alternative (https://github.com/ctf0/laravel-mix-versionhash) wouldn't it be interesting for Laravel-mix to make this model official?

**Comment by ankurk91** [comment]
i am using this one
https://github.com/medz/webpack-laravel-mix-manifest#readme

**Comment by OwenMelbz** [comment]
Query strings are nice and simple for most use cases, and work nicely when people want to git ignore the `app.js` etc - rather than having a plethora of a thousand files generated that then need to be cleaned up.

As @ankurk91 suggested, can use other options if the default isn't suitable for your project

**Comment by JosuelRocha** [comment]
In this case, Laravel-mix could have a configuration property in webpack.mix.js to choose whether to hash in the query string or filename, and also set the hash size ([hash:8], [hash:32], etc).

Because extensions for Laravel-mix do this work only on .js and .css files, unlike Laravel-mix itself which does it on all files, especially images and fonts within .css files.

What do you think @JeffreyWay?
