### ISSUE TITLE
inProduction, mix.copyDirectory is not copying minified version of JS

### ISSUE THREAD

**Issue by rickertl** [JeffreyWay/laravel-mix#2342]
-   Laravel Mix Version: 4.1.4
-   Node Version: 10.7.0
-   NPM Version: 6.14.2
-   OS: macOS 10.14.6

### Description:
In Production, I am using ‘mix.scripts' to combine 3 source JS files into 'js/all-scripts.js' and then using ‘copyDirectory' to duplicate this combined script at 'public/js’. Upon ‘npm run production', the 'js/all-scripts.js' is updated & minified (expected), but the ‘public/js/all-scripts.js’ is updated but NOT minified (unexpected).

I have worked around it by duplicating my ‘mix.scripts’ declaration and having the destination be ’public/js/all-scripts.js’, but seems I shouldn’t have to.

Am I missing something?

### Steps To Reproduce:
if (mix.inProduction()) {
mix.scripts([
    'src/js/script1.js',
    'src/js/script2.js',
    'src/js/script3.js'
], 'js/all-scripts.js’)
.copyDirectory('js’, ‘public/js’)
};

**Comment by yneet** [comment]
@rickertl, do you have others files in directory js?

Have you test this code:
`mix.js([...], 'public/js/all-scripts.js')`

**Comment by rickertl** [comment]
@yneet Yes, I have other scripts in the 'js' directory. I keep some separate that are only loaded for particular views.

I have tried mix.js, but it seems to fail with processing/combining bootstrap source. mix.scripts has no issue with that.

Thanks for the reply.

**Comment by Chopinsky** [comment]
This problem sounds like a typical JavaScript async-problem, where minifiying a combined file requires disk IO, which could finish after the copy operation, and this would be a problem if the file-minification task and copy task are not using synchromized APIs. 

I'm not very familiar with this library, so if you could point me to the locations where the minification and copy tasks are generated, I can dig deeper on this issue.

**Comment by rickertl** [comment]
@Chopinsky Your assessment sounds logical. That's what it seemed to me. Things were not happening in the correct order and if not dependent on one completing before the other (minify before copy), the odd result makes sense. 

Not sure where to point you. Perhaps someone else can help?

Thanks.

**Comment by Chopinsky** [comment]
I think I spotted the issue: 

1. in `CustomTasksPlugin.js`, where build tasks are executed, we are looping over all scheduled tasks one after another. And for this particular issue, the file combination task and copy task will be executed consecutively at this point:

https://github.com/JeffreyWay/laravel-mix/blob/40eaa995485871cee55a366e1305ae945dfbc458/src/webpackPlugins/CustomTasksPlugin.js#L12

2. then a few lines later, we will check if we're running in production; and if so, we will minify the assets files:

https://github.com/JeffreyWay/laravel-mix/blob/40eaa995485871cee55a366e1305ae945dfbc458/src/webpackPlugins/CustomTasksPlugin.js#L19

And these lines have explained what we saw in this issue: the files will be combined and copied into the destination directory, and then minified, which leaves the minified files in the source directory (because the copy task has already completed), but the copied over files are not minified. 

This would also why the workaround actually works: on the 2nd run, we're combining the minified source files (they're minified after the 1st combine-copy tasks are done), and then copy the combined as well as minified files to the destination directory.

So here are a few possible fixes:
1. right now the minifier would skip the copy task, so the easiest fix is to remove the exclusion filter at [line #55](https://github.com/JeffreyWay/laravel-mix/blob/40eaa995485871cee55a366e1305ae945dfbc458/src/webpackPlugins/CustomTasksPlugin.js#L55), and let the minifier also run on the copied over files.

2. we can defer the copy tasks after the minifier is run, however, this may impact downstream tasks depending on the copy tasks;
