### ISSUE TITLE
Extract don't work as expected

### ISSUE THREAD

**Issue by natocTo** [JeffreyWay/laravel-mix#242]
Hello, I have problem with use of extract function. See the examples.

Basis example:
```
mix.setPublicPath('www')
   .js('resources/js/admin/main.js', 'www/js/admin.js')
   .js('resources/js/front/main.js', 'www/js/app.js')
   .version();
```

And output:
```
/js/admin.015f8cbc09d2b83f994b.js    1.44 MB       0  [emitted]  [big]  /js/admin
/js/app.be3db859e3d3ea48f9e1.js       299 kB       1  [emitted]  [big]  /js/app
             mix-manifest.json      108 bytes         [emitted]
```

Now example with extract() function.
```
mix.setPublicPath('www')
   .js('resources/js/admin/main.js', 'www/js/admin.js')
   .js('resources/js/front/main.js', 'www/js/app.js')
   .extract(['vue', 'vuex', 'vue-lazyload', 'lodash', 'axios'])
   .version();
```

Here is output. You can see that size of app.js is same like before. Also there is no manifest file which you are mentioned in documentation (manifest, vendor, app).
```
 /js/admin.4a371f6dfa9c09086f1c.js    1.44 MB       0  [emitted]  [big]  /js/admin
   /js/app.14e39db9afc93d0f5c2e.js     299 kB       1  [emitted]  [big]  /js/app
\js\vendor.98409f08cf049c73b502.js     178 kB       2  [emitted]         \js\vendor
                 mix-manifest.json  165 bytes          [emitted]
```

I have WIndows 10, node v7.4.0. Laravel mix 0.6.0.

**Comment by JeffreyWay** [comment]
I just ran your exact webpack.mix.js file, and got this:

https://www.dropbox.com/s/jsdy5in75bjzp7z/Screenshot%202017-01-31%2010.12.47.png?dl=0

I'm guessing it's because, somehow, you have those backslashes in your output. Can you confirm that you're using version 0.6.0 of Laravel Mix (or higher)? If not, please upgrade and try again.

Also, if you copied the webpack.config.js file to your project root, make sure that it is up-to-date with ours.

https://github.com/JeffreyWay/laravel-mix/blob/master/setup/webpack.config.js

**Comment by natocTo** [comment]
I removed node_modules and install all over again. Now it is working fine. Thx
