### ISSUE TITLE
Unresolved function or method js

### ISSUE THREAD

**Issue by boskiv** [JeffreyWay/laravel-mix#2438]
-   Laravel Mix Version: 5.0.4
-   Node Version (v12.18.0):
-   NPM Version (6.14.6):
-   OS: OSX 

### Description:
Is it possible to add js and sass to public API ?

### Steps To Reproduce:
I have an errors in Phpstorm when open file
```
Unresolved function or method js() 
Unresolved function or method sass() 
```
![Screen Shot 2020-07-10 at 5 36 51 PM](https://user-images.githubusercontent.com/1939783/87208466-703b2100-c2d4-11ea-9331-150f17de49cd.png)

**Comment by absolunet-puller** [comment]
This behavior happens because `js` and `sass` methods are dynamically added to the Laravel Mix API, through components, making IDE autocompletion nearly impossible by default.

A valid solution tough would be to add JSDoc blocks inside the component files that would link the component methods to the API instance for IDE autocompletion.

```javascript
/**
 * Compile JavaScript file.
 *
 * @method js
 * @param {string} entry - The entry file.
 * @param {string} output - The output file name.
 * @returns {Api} The current Laravel Mix API instance.
 * @memberof Api
 * @instance
 */
```

**Comment by thierry2015** [comment]
This behavior happens because `js` and `sass` methods are dynamically added to the Laravel Mix API, through components, making IDE autocompletion nearly impossible by default.

A valid solution tough would be to add JSDoc blocks inside the component files that would link the component methods to the API instance for IDE autocompletion.

```javascript
/**
 * Compile JavaScript file.
 *
 * @method js
 * @param {string} entry - The entry file.
 * @param {string} output - The output file name.
 * @returns {Api} The current Laravel Mix API instance.
 * @memberof Api
 * @instance
 */
```
