### ISSUE TITLE
Laravel mix production working on local server but not remote

### ISSUE THREAD

**Issue by FreddyCrugger** [JeffreyWay/laravel-mix#2479]
Hello,

I am having a weird issue, when I try to version my app.js and custom.css it works locally(even when compiled in production), but as soon as I upload all the files from the public folder to my public_html in the remote, the versioning of the files do not working.
npm run production

```
   "laravel/framework": "6.2",
    "laravel-mix": "^5.0.5",
```
Here is what I tried:

webpack:
```
mix.js('resources/js/app.js', 'public/js')
   .sass('resources/sass/app.scss', 'public/css')
   .styles(['resources/css/custom.css'], 'public/css/custom.css');

if (mix.inProduction()) {
    mix.version();
}
```
Also tried this:
```
mix.js('resources/js/app.js', 'public/js')
   .sass('resources/sass/app.scss', 'public/css')
   .styles(['resources/css/custom.css'], 'public/css/custom.css');

mix.version();
```
In my blade files:

I tried:
```
<script src="{{ asset(mix('css/custom.css')) }}"></script>
<script src="{{ asset(mix('js/app.js')) }}"></script>
```
and
```
<script src="{{ mix('css/custom.css') }}"></script>
<script src="{{ mix('js/app.js') }}"></script>
```
As I said it is working on my local but not on the production server.

I compile everything locally and upload all to the remote.

Is there a file on the local that is needed on the remote for this to work correctly please?

Thank you.

**Comment by JeffreyWay** [comment]
Make sure your mix-manifest.json file is being uploaded to your server. 

Without know the exact error you’re seeing, it’s difficult for me to order any other hints.

**Comment by FreddyCrugger** [comment]
Yes it has been uploaded. And no errors are output. 
I have opened a thread here but no luck either:
https://laracasts.com/discuss/channels/laravel/bug-in-laravel-6-laravel-mix-version-working-locally-but-not-in-remote

**Comment by adriaanzon** [comment]
I just ran into a problem like this too, after doing some npm library upgrades. The build was running fine locally, but when deploying on a 1GB DigitalOcean instance, it failed without a clear error.

Turned out it was running out of memory. I confirmed this by monitoring `htop` while the build process was running.

I solved it by simply freeing up some memory. In this case I disabled an unneeded service (`snapd`) and restarted a long-lived service that had been eating up some RAM over time (`php7.4-fpm`). To prevent this from happening in the future, I am considering to move the build process over to GitHub Actions.
