### ISSUE TITLE
Module not found: Error: Can't resolve 'popper.js' -> Bootstrap 4 + PopperJs

### ISSUE THREAD

**Issue by molerat619** [JeffreyWay/laravel-mix#2593]
-   Laravel Mix Version: 4.1.4
-   Node Version: 12.16.3
-   NPM Version: 6.14.4
-   OS: MacOs

### Description:
I'm trying to use a JS component from Bootstrap 4 which requires popperjs. The current popperjs package is called `@popperjs/core` and I assume that is the reason why webpack throws this error:

```
ERROR in ./node_modules/bootstrap/dist/js/bootstrap.js
Module not found: Error: Can't resolve 'popper.js' in '/Users/myuser/Sites/sthr-website/node_modules/bootstrap/dist/js'
 @ ./node_modules/bootstrap/dist/js/bootstrap.js 7:101-121
 @ multi jquery @popperjs/core bootstrap lazysizes wowjs @splidejs/splide
```

This is my configuration:

```
mix.js([
    'source/_assets/js/main.js',
    ...
], 'js')
    .extract([
        'jquery',
        '@popperjs/core',
        'bootstrap',
        'lazysizes',
        'wowjs',
        '@splidejs/splide'
    ])
    .copy([
        'node_modules/@mdi/font/fonts/**/*'
    ], 'source/assets/build/fonts')
    .sass('source/_assets/sass/main.scss', 'css')
    .options({
        processCssUrls: false,
    })
    .version();
```

Similar issues but with decent solutions that I dislike: https://stackoverflow.com/questions/46022976/cant-load-popper-js-with-webpack-and-laravel-mix

How can I make bootstrap find the popperjs package?

**Comment by thecrypticace** [comment]
This is because Bootstrap 4 requires popper.js 1.x whose package is named 'popper.js'. `@popperjs/core` is version 2.x. It appears that Bootstrap 5 will be upgrading to popper 2 but that hasn't been completed yet.

In the mean time install `popper.js` instead of `@propperjs/core`. The solution you see on Stack Overflow is exactly what I'd recommend for Mix + Popper v1.

Closing as this is not a Mix issue.

**Comment by molerat619** [comment]
Thanks @thecrypticace - that was it...
