### ISSUE TITLE
cp: cannot stat 'node_modules/laravel-mix/setup/webpack.mix.js': No such file or directory

### ISSUE THREAD

**Issue by ParveenMalethia** [JeffreyWay/laravel-mix#2681]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`)
-   Node Version (10.19.0):
-   NPM Version (6.14.10):
-   OS: ubuntu

### Description:
i tried running the copy command its not working and when i saw in the node_moudels/laravel-mix/setup 
there is on webpack.config.js
not the webpack.mix.js

### Steps To Reproduce:
npm install laravel-mix --save-dev
cp node_modules/laravel-mix/setup/webpack.mix.js ./

**Comment by erickleinde** [comment]
Hi @ParveenMalethia 

from the latest version you have to create the webpack.mix.js manually

The documentation is still for version 5.0, but npm is already distributing version 6. At the top right of the documentation you can change it to version 6 and then everything is correct again.

Hope I could help you :)

**Comment by AjeyataVerma** [comment]
creating it manually works but then the whole file is empty all way. What to do about that. there's no code to work on!

**Comment by erickleinde** [comment]
> creating it manually works but then the whole file is empty all way. What to do about that. there's no code to work on!

hi @AjeyataVerma

In the [documentation ](https://laravel-mix.com/docs/6.0/installation)you can switch from version 5 to version 6 in the upper right corner, everything is described there.

Since there are changes in version 6, it is quite good to read the documentation at https://laravel-mix.com/docs/6.0/installation
