### ISSUE TITLE
Fixed! webpack not mix multiple js, only work as app.js @laravel 8

### ISSUE THREAD

**Issue by martinym28** [JeffreyWay/laravel-mix#2878]
-   Laravel Mix Version: 6.0.13 
-   Node Version v12.18.3
-   NPM Version v6.14.6:
-   OS: windows 10

### Description:
------ 
```
mix.js('resources/js/app.js', 'public/js') //work fine
    .js('resources/js/back.js', 'public/js') //did not update @ npm run watch or npx mix watch --poll after the second time，but work in the first and second time. strange?
    .vue()
    .sass('resources/sass/app.scss', 'public/css');
```
### Steps To Reproduce:
It worked at laravel 7 with Laravel Mix Version: 5
reinstall system or laravel 8 a few times but could not be resolved. 
any change get: **webpack compiled successfully**
but public/back.js while still keep early time without change.

now I have to mix it as **npm run dev** repeatedly
### vue install steps
composer create-project laravel/laravel example-app
composer require laravel/ui
php artisan ui vue --auth
npm install
npm run dev

**Comment by martinym28** [comment]
fixed, because of disableNotifications on. then I add 

**mix.disableNotifications();** to webpack.mix.js

all work normal !

**Comment by gaarlos** [comment]
Hi @martinym28, Disabling notifications worked for me too! But the issue is not solved, this is just an (annoying) workaround...

@JeffreyWay there is a problem with `disableNotifications()` and `disableSuccessNotifications()` functions, calling them makes mix not include manifest.js and vendor.js in mix-manifest.json, so Laravel throws an error because It can't find anything :(
