### ISSUE TITLE
Add folder to watch

### ISSUE THREAD

**Issue by tiagomatosweb** [JeffreyWay/laravel-mix#294]
Hi, any idea how I would add other directories to be watched?

**Comment by JeffreyWay** [comment]
You can't right now, unless you copy our webpack.config.js file to your project root, and maintain it yourself.

**Comment by sebastiaanluca** [comment]
Any update to this issue? Perhaps using `mix.webpackConfig()` somehow?

**Comment by tiagomatosweb** [comment]
```
mix.browserSync({
   files: ['file.js']
});
```

It does the trick. More info https://browsersync.io/docs/options

**Comment by dharkness** [comment]
@tiagomatosweb doing this doesn't rebuild JS/CSS files from sources, nor does it even cause the browser to refresh. I'm watching `.env` and a SASS variables file that gets symlinked into the SASS build pipeline, and changing either one does nothing.

**Comment by tiagomatosweb** [comment]
Mm.. not sure! It was a workaround while ago. Do not remember if it recompile everything once those files set in browserSycn object are updated. Sorry mate.

**Comment by ajnozari** [comment]
Is there anything we can do about this?  It is clearly still an issue as subfolders are not watched at ALL by npm run watch.

I have managers in resources/js/managers.  If I move the files to root, they are watched, but if they are put into the managers subfolder they are completely ignored.

**Comment by tiagomatosweb** [comment]
I think the webpack HMR can be used/extended 
[https://webpack.js.org/guides/hot-module-replacement](url)

**Comment by sadeghbarati** [comment]
> ```
> mix.browserSync({
>    files: ['file.js']
> });
> ```
> 
> It does the trick. More info https://browsersync.io/docs/options

it's just reload and not trigger laravel-mix compiling

**Comment by withoutwax** [comment]
> @tiagomatosweb doing this doesn't rebuild JS/CSS files from sources, nor does it even cause the browser to refresh. I'm watching `.env` and a SASS variables file that gets symlinked into the SASS build pipeline, and changing either one does nothing.

Any updates on this?
I think this issue seems quite important with to developers who is using Tailwind 3 with laravel-mix, where laravel-mix only watches css, sass or js for compilation, not for twig or blade files. Tailwind 3's purging classes that are not being use is great for production, but it's unfortunately have a drawback for a project with dev environment that doesn't trigger recompilation with a file that has html in it. In such cases, when classes are added / removed, it needs to trigger a compilation, for example by saving an unchanged sass file or js file, to see the newly added class to take effect.

**Comment by thecrypticace** [comment]
@withoutwax Adding files to your `content` config will watch them. If this does not work please open a separate issue and provide a reproduction. It would be quite helpful.
