### ISSUE TITLE
Missing `API` type in component.d.ts

### ISSUE THREAD

**Issue by Elhebert** [JeffreyWay/laravel-mix#2954]
-   Laravel Mix Version: 6.0.9
-   Node Version: v15.12.0
-   NPM Version: 7.6.3
-   OS: Windows 10 (WSL2 w/ Ubuntu 20.04)

### Description: 

When compiling a Typescript component into js (to be published on npm) `tsc` complains about a missing type in the component.d.ts

```bash
node_modules/laravel-mix/types/component.d.ts:76:11 - error TS2304: Cannot find name 'API'.

76     (mix: API, config: webpack.Configuration, ...args: any[]): void;
             ~~~


Found 1 error.
```
I've tried to see if I could import API from the index file in the component.d.ts file, but didn't manage to make it work so far.

### Steps To Reproduce:

Add typescript as a dependency, add a tsconfig file and run the `tsc` command.

This branch can be used to replicate the problem: https://github.com/Elhebert/laravel-mix-sri/tree/typescript-rewrite

**Comment by thecrypticace** [comment]
👀 whoops. Thanks for catching that.

I can't import the namespaces exports because we use an export assignment. I can do `typeof api` instead of `Api` but that seems really wrong. I'm guessing the best solution would be to move the API definition to its own file and leave index.d.ts basically empty with the API import / export assignment. I had done this initially but I wasn't too fond of the anemic index.d.ts file. It seemed handy to have all the API definitions in that one file. Thoughts?

Aside: It'd be preferable to not use import from `laravel-mix/src` (like the `File` import) if you can help it. In this case I'd use `fs` directly instead. It's not going away right now but it's an incomplete abstraction. What we really need is a filesystem-like abstraction that doesn't depend on globals like `File` does. It's just something I've had on my mind for a bit.

**Comment by Elhebert** [comment]
@thecrypticace I made a PR before I saw your answer. I do agree that `typeof api` is not a good solution. I do think that it's a good temporary solution to fix the current broken types.

The ideal solution is, as you proposed, to have the API definition as its own export. It doesn't have to be in a different file tho.

**Comment by thecrypticace** [comment]
All good! I agree the temporary fix is a reasonable solution for now.

It's my understanding that it does if we have an export assignment like we use at the bottom of `index.d.ts` otherwise you'll get an error:
<img width="845" alt="Screen Shot 2021-04-28 at 17 45 21" src="https://user-images.githubusercontent.com/614993/116476654-82795200-a849-11eb-92d0-7a8b9a1a60f2.png">

Do you know of a way around that?

**Comment by Elhebert** [comment]
My knowledge of type declaration is fairly limited. I tried something that seems to work:

```ts
export declare namespace mix {
```

Then:

```ts
// component.d.ts

import { mix } from, './index'
```

this allow us to then call `mix.Api` as a valid type.

**Comment by Elhebert** [comment]
And just noticed that then we can't `export = api` 🤔 

I'm just bad 😂

**Comment by thecrypticace** [comment]
😂

**Comment by thecrypticace** [comment]
I'll probably end up moving it to a separate file in the future. Seems to be the easiest "correct" solution
