### ISSUE TITLE
Default devserver to HTTPS for Chrome 92

### ISSUE THREAD

**Issue by HollyIT** [JeffreyWay/laravel-mix#2987]
-   Laravel Mix Version: any
-   Node Version: any
-   NPM Version: any
-   OS: any

### Description:

Starting in Chrome 92 (slated for release in the end of July), access to resources over private networks must be made via HTTPS, even if the site is on HTTP. This means running things like hot will no longer work, unless the assets are served via HTTPS.

This will mostly affect Mix and not the larger Webpack devserver ecosystem, as most Webpack devserver projects serve both the page and resources from the same domain/port (ie: Vue CLI devserver). 

Of course this new Chrome "feature" presents the other big problem - the need for certificates or accepting insecure connections from localhost (or start Chrome with the --allow-insecure-localhost flag, which allows a bad certificate, but doesn't stop the original problem). Not really sure how we can overcome that one, except for big, flashing warnings the people will certainly ignore.   

### Steps To Reproduce:
Install Chrome Canary and try to run a project with hot. No javascript or css will load. Hot must start with HTTPS.

**Comment by thecrypticace** [comment]
In Chrome access to localhost from a non-localhost IP _already_ requires HTTPS on the part of the origin domain (but can be disabled) because localhost is currently considered a secure context which is why some things that are "https-only" also work on http://localhost). Are you saying localhost itself will now need a certificate? The Private Network Access doesn't seem to imply that.  Unless I'm misunderstanding, from what I can tell we need to adjust the HMR server to add a header to the appropriate response to OPTIONS: `Access-Control-Request-Private-Network: true` (and a few other CORS headers) which seems like something webpack-dev-server should do.

The relevant RFC can be found here: https://wicg.github.io/private-network-access/

**Comment by HollyIT** [comment]
Ahh you are right. Totally forgot I had my test domain pointing to my NAT for testing on mobile devices. So long as everything is pointing to the same IP, there is no problem. I'm going to close this as it is more an edge case.
