### ISSUE TITLE
laravel mix add hash to the name of font file in output css

### ISSUE THREAD

**Issue by pixieaka** [JeffreyWay/laravel-mix#384]
=== App.scss file ===
![p](https://cloud.githubusercontent.com/assets/17777237/22963557/57e4d63c-f35c-11e6-8bf1-9cc204fdb1d8.JPG)

=== Output ===
![p1](https://cloud.githubusercontent.com/assets/17777237/22963377/7f2b3a8e-f35b-11e6-9023-5c609fa99bcd.JPG)

=== Browser page source code ===
![p2](https://cloud.githubusercontent.com/assets/17777237/22963390/94d5b13e-f35b-11e6-8920-383901fa83a4.JPG)

=== Output css folder in public directory  ===
![p3](https://cloud.githubusercontent.com/assets/17777237/22963392/9770a0c0-f35b-11e6-9b66-d3e4ea59eab1.JPG)

=== Result in browser ===
![p5](https://cloud.githubusercontent.com/assets/17777237/22963400/9dd7a6de-f35b-11e6-9b10-408f89c372b5.JPG)

=== glyph font in bootstrap-sass also ===
![pkk](https://cloud.githubusercontent.com/assets/17777237/22964032/19eb84f4-f35f-11e6-8bf6-ba59bba3e633.JPG)

=== My webpack.mix.js ===
![ll](https://cloud.githubusercontent.com/assets/17777237/22964244/3b927f3a-f360-11e6-83e9-9c5e08dfd2fa.JPG)

**Comment by JeffreyWay** [comment]
That's for cache-busting purposes. It won't break anything. 

I think what you're seeing is unrelated to the query. I just created a fresh project, installed font-awesome, compiled everything down, and then added:

```html
<i class="fa fa-music">
```

to the page. It all worked.

**Comment by pixieaka** [comment]
I think it problem on Windows system only.

**Comment by pixieaka** [comment]
on chrome 56.0.2924.87 (64-bit)
![1](https://cloud.githubusercontent.com/assets/17777237/23000938/873449c4-f3eb-11e6-8902-930e58e1776b.JPG)

on edge 38.14393.0.0
![2](https://cloud.githubusercontent.com/assets/17777237/23000968/977b0caa-f3eb-11e6-974d-5a5e99acbee5.JPG)

**Comment by pixieaka** [comment]
![aa](https://cloud.githubusercontent.com/assets/17777237/23009777/967a809e-f420-11e6-85f6-f71588f63878.JPG)

**Comment by shulard** [comment]
Maybe you just need to define the `APP_URL` Laravel constant to `http://pixie/app/public/` ?

**Comment by pixieaka** [comment]
No the problem not in APP_URL because ( css \ js ) files is OK. but the problem in fonts only.

**Comment by bitdagger** [comment]
If you take off the leading `/` in your CSS (`fonts/blah` instead of `/fonts/blah`) does it fix the problem?

**Comment by kohenkatz** [comment]
@pixieaka You need to use the `mix.setResourceRoot` function to fix this.

By default, Mix's Webpack configuration adds a leading slash to the paths to fonts and images. Setting a different path (don't forget leading and trailing slashes) using the function I mentioned will use the path you set instead of a single `/`.

**Comment by kohenkatz** [comment]
Typically though, you should try to avoid a setup like this - instead set IIS to use the `app\public` folder as the web root. If you don't do that, you're going to get people who are trying to explore your project's hidden parts by searching for files above the `public` directory.

**Comment by eblin** [comment]
@pixieaka Your problem is exactly what @kohenkatz described with your server being configured wrong.

The reason everything works fine when you run `php artisan serve` is because laravel is really just setting up the built-in php server to run the `server.php` (in the root of your project you can see this file), which routes everything to `public/index.php`

This is the recommended setup as mentioned in the docs:

> Public Directory
> After installing Laravel, you should configure your web server's document / web root to be the public directory. The index.php in this directory serves as the front controller for all HTTP requests entering your application.

you can see how this works at `vendor/laravel/framework/src/Illuminate/Foundation/Console/ServeCommand.php` 

Just set your webroot in your server to go to `public` folder 👍

**Comment by pixieaka** [comment]
Thank you guys for help me . The problem is solved.

**Comment by grupoCatolicaInf** [comment]
@pixieaka  how did u fix that, i couldnt understand what @kohenkatz mean, i do not main english sorry

**Comment by gtempesta** [comment]
If for some reason you need to remove cache busting only for fonts, you can find my solution here: https://github.com/JeffreyWay/laravel-mix/issues/2036
