### ISSUE TITLE
Not really an issue...

### ISSUE THREAD

**Issue by CKLFP** [JeffreyWay/laravel-mix#396]
@JeffreyWay Hi,
Like I said, this is not an issue is lack of understanding, but laravel-mix doesn't feel  natural, intuitive like I felt with elixir. .styles no longer exists..., mix breaks my assets structure creating new folders for images an fonts... it throws allot of fs.js error messages... with elixir everything was more natural and intuitive.
I repeat like I said this is NOT an issue.
what I did was yarn remove laravel-mix then yarn add laravel-elixir... now every thing works ok again.
Thanks.

**Comment by JeffreyWay** [comment]
> Like I said, this is not an issue is lack of understanding

It somewhat is.

> .styles no longer exists

`Mix.combine()` is the equivalent, and does the same thing. I have a task to add Mix.styles() back in, but it will simply be an alias for `Mix.combine()`.

>  mix breaks my assets structure creating new folders for images an fonts

This is a feature of Webpack's, and is entirely dependent upon how you write your CSS. If you're referencing relative paths to assets, it'll copy those assets to your public directory.

> it throws allot of fs.js error messages

You can create an issue here with the exact error message, and we can figure out what the problem is.

**Comment by CKLFP** [comment]
@JeffreyWay Hi,
hanks for you fast answer, right now I have what I  need running, I with my time really tight so I will not create that issue, but I have a little project of my own and as some as possible I will give it a try again.
I don´t now if this is the proper channel, to best communicate with you, sorry if not.
Once again thank you.
