### ISSUE TITLE
Issue on NPM Install

### ISSUE THREAD

**Issue by stevepop** [JeffreyWay/laravel-mix#42]
I had the following errors while installing laravel-mix on a fresh Laravel 5.3 installation.
`UNMET PEER DEPENDENCY webpack@2.2.0-rc.3`

```
npm WARN extract-text-webpack-plugin@2.0.0-beta.4 requires a peer of webpack@^2.1.0-beta.19 but none was installed.
npm WARN webpack-dev-server@2.1.0-beta.12 requires a peer of webpack@^2.1.0-beta.26 but none was installed.
```
node version: 6.9.2
npm version: 3.10.8

I have not been able to go further than this.

**Comment by matthijs110** [comment]
Try to install webpack 2.2.0 manually:

`npm install webpack@2.2.0-rc.3`

**Comment by QWp6t** [comment]
When you say that you "have not been able to go further than this," what exactly did you try doing? Those are just warnings, not errors. You can sometimes ignore them because the peer dependency might wind up getting satisfied, which should be the case here because [laravel-mix should be installing webpack for you](https://github.com/JeffreyWay/laravel-mix/blob/70210/package.json#L48).

If webpack isn't getting installed by laravel-mix, then you can install webpack (same goes for any other peer dependency) manually as noted above. If webpack IS getting installed, but you're still having issues, then that's something worth looking into, but by all accounts this seems like it's probably a user error, not a bug.

**Comment by konovalov-nk** [comment]
@stevepop
Try:

`npm install --global webpack webpack-dev-server`

Solved the issue for me.

**Comment by stevepop** [comment]
Thanks guys I had to install webpack 2.2.0 manually and it worked.
