### ISSUE TITLE
Compiled CSS file has @CHARSET after a font import...caused by bootstrap?

### ISSUE THREAD

**Issue by weldricks** [JeffreyWay/laravel-mix#453]
- Laravel Mix Version: 0.8.1
- Node Version 7.5.0 
- NPM Version  4.1.2
- OS: Windows 10

### Description:

Fresh install!

When I run npm run dev in the compiled styles.css I get this issue:

**@import url(https://fonts.googleapis.com/css?family=Raleway:300,400,600);@charset "UTF-8";**

It appears to be adding the charset after an import where it should be first. If you delete the bootstrap import this goes away...

### Steps To Reproduce:

styles.scss

// Fonts
@import url(https://fonts.googleapis.com/css?family=Raleway:300,400,600);

// Variables
@import "variables";

// Bootstrap
@import "node_modules/bootstrap-sass/assets/stylesheets/bootstrap";

npm run dev

**Comment by JeffreyWay** [comment]
Not entirely sure why it comes after, but it must be related to the fact that it's a absolute import to that Google font. Those must be hoisted to the top or something. 

Either way, this isn't something that Mix has control over.

**Comment by huqiaovancouver** [comment]
I had the exact same error where charset appears after the font import, after a fresh install. I'm surprised that this issue hadn't been brought up by many others. I had to comment out the font import line to avoid the error. If this is not controlled by Mix, what could be the root cause?

- Laravel Mix: 4.0.7
- Node: 8.10.0
- npm: 3.5.2
- OS: macOS 10.14.2

**Comment by nidhi-parihar** [comment]
I tried deleting @import url(https://fonts.googleapis.com/css?family=Nunito);@charset "UTF-8"; from app.css but as soon as I do npm run watch, the url comes back again with the same error. Please help as I've been trying to solve this error since so long

**Comment by Awais512** [comment]
Same issue, When i run npm run dev it comes back and gave error and style can't be applied.

**Comment by ridwantanjung** [comment]
same here, it still happened in 2019, how to fix it?

**Comment by feliperamaral** [comment]
same here, it still happened in 2020, how to fix it?

**Comment by jochantrelle** [comment]
Anybody figured this out yet? 

Having the same phantom @charset "UTF-8"; to appear after google font @import consequently giving me this css waring in my FireFox (sorry still using this) console: "Ruleset ignored due to bad selector." 

Doesn't seem to having any unwanted side-effects, I get my fonts anyway, however, ODC says it (@charset) should not be magically appearing in my code...

Any help is appreciated. 
Thanks in advance,

**Comment by moranot** [comment]
Have you checked the SASS files in your Laravel application?

/app/resources/sass/app.scss

![image](https://user-images.githubusercontent.com/50932745/88879622-c1b23e00-d1f8-11ea-95fc-6c05dde3f010.png)

**Comment by Cerebrofagia** [comment]
I tried to reverse the two lines and now it seems to work

![image](https://user-images.githubusercontent.com/68775741/92154466-1cf1d480-ee26-11ea-96af-e4707a5c0d16.png)

**Comment by MetodiEterov** [comment]
Hi All,
The problem still exists on my side. Even in a fresh installation of a Laravel project and after executing "npm run dev" command, the error appears again. Even when I swapped the positions of the two rows above, as described in the previous example, the error appears again. Does anyone know how to solve the problem?
Thanks.

**Comment by yodahack** [comment]
you are most probably adding stylesheet as javascript in your HTML file

ROTFL

**Comment by adrienne** [comment]
This bug is still present, although it seems likely to be upstream in node-sass. (And no, I'm not pulling any Javascript into my CSS file accidentally.)
