### ISSUE TITLE
Mix not working with latest Vue, which we auto-update to (vue-template-compiler mismatch)

### ISSUE THREAD

**Issue by ThomHurks** [JeffreyWay/laravel-mix#480]
- Laravel Mix Version: 0.8.7
- Node Version (`node -v`): 7.6
- NPM Version (`npm -v`): 4.2
- OS: MacOS Sierra

### Description:

With Laravel's default package.json, we auto-update to Vue 2.2.1 when you use "npm update". However, this version of Vue is incompatible with vue-template-compiler 2.1.10, which Mix uses. This means we get an error and cannot compile our assets.

### Steps To Reproduce:

- npm update
- npm run dev

**Comment by ThomHurks** [comment]
I solved this issue for me by removing laravel-mix and reinstalling it. Probably because it then gets the newer version of the dependency vue-template-compiler? This is probably still going to confuse some people.

**Comment by JeffreyWay** [comment]
Thanks - I'll think about how to make that more clear.

**Comment by msonowal** [comment]
@JeffreyWay any updated on this? It will be very helpful
sorry to bother you

**Comment by Bomavi** [comment]
Any updates? Just updated Vue to 2.4.2 and now here is conflictes with vue-tamplate-compiler@2.3.4...

It's stuped, because I updated vue-tamplate-compiler globally, I updated it locally for laravel-mix... I deleted node_modules and re-installed them... nothing, all the time the same error... where you hardcoded it? How to fix it?
