### ISSUE TITLE
.sass() method does not accept array of files as source

### ISSUE THREAD

**Issue by ankurk91** [JeffreyWay/laravel-mix#512]
- Laravel Mix Version: 0.8.2
- Node Version (`node -v`):  6.9.1
- NPM Version (`npm -v`):  3.10.8
- OS: Ubuntu 16.04 x64

### Description:
```.sass()``` method does not accepts array of files as source
Laravel Elixir already  allow this.

### Steps To Reproduce:
I was trying to generate single css vendor file
```js
mix.sass([
'resources/assets/bootstrap/scss/bootstrap.scss',
'node_modules/font-awesome/scss/font-awesome.scss',
],'css/vendor.min.css')
```
I have tweaked the bootstrap variables,
```sass
@import "variables";
@import "../../../../node_modules/bootstrap-sass/assets/stylesheets/bootstrap.scss";
```

Please let me how can i achieve this.

**Comment by terrylow** [comment]
why not just add font-awesome import statement directly to bootstrap.scss ? it serve no different

**Comment by ankurk91** [comment]
Ok,
I just ended up with creating a ```resources/assets/scss/vendor.sass``` file like -
```sass
@import "variables";
@import "../../../../node_modules/bootstrap-sass/assets/stylesheets/bootstrap.scss";
// import all regular css files like this (without extension)
@import "../../../../node_modules/font-awesome/css/font-awesome.min";
```
Thanks for the tip.

**Comment by Remo** [comment]
There's one benefit, being able to specify an array would allow us to dynamically set the variables file. This would be helpful if you had multiple targets with different variables. Trying to figure out how to do that and landed here, but no solution ;-)

**Comment by ruchern** [comment]
@Remo Alternatively you can follow @ankurk91 by creating one global sass file and importing it's respective sass files in it.

**Comment by Remo** [comment]
@ruchern I wanted to dynamically set the name of the variables file. I've now created two main scss files which then load the different variables. Not the solution I was looking for, but it works.

**Comment by dharkness** [comment]
I was hoping for the same ability as @Remo. We have two news sites that use the same codebase with a variables file for each to provide the skinning.

While we could provide two top-level files for each SASS file, there are currently eight SASS files because some pages need extra CSS that we don't want to put in the global file. This means sixteen extra files instead of being able to specify the variables file dynamically. The other option is to have each developer (and the deployment system) create a symlink to the active variables file which is what we'll probably do.

Supporting an array of files seems the better path since `scripts()`, `js()`, and `babel()` already do so.
