### ISSUE TITLE
require node modules fonts folder shought be configurable

### ISSUE THREAD

**Issue by pavinthan** [JeffreyWay/laravel-mix#514]
Hi Jeffrey,

I think laravel mix is a best one for front end development but when I 
require('bootstrap-sass'); or
@import "~font-awesome-sass/assets/stylesheets/font-awesome"

the font folder copy to public/fonts it's shought be configurable if it's possible  please look into this ASAP

**Comment by JeffreyWay** [comment]
We can make it configurable, but what's the use case here? Webpack will automatically rewrite your font urls() to point to that directory.

**Comment by pavinthan** [comment]
I need to copy the fonts to "public/assets/fonts" but it copy to "public/fonts" how can I configure?

**Comment by QWp6t** [comment]
Use `mix.copy()` ?

**Comment by pavinthan** [comment]
I did it already but no luck

// Fonts
const publicFontPath = "public/assets/fonts/";
mix.copy(nodeModulePath + 'bootstrap-sass/assets/fonts/bootstrap', publicFontPath);
mix.copy(nodeModulePath + 'font-awesome-sass/assets/fonts', publicFontPath);

**Comment by devcircus** [comment]
just copy webpack.config.js from your node_modules/laravel-mix/setup folder to your project root. Then you can modify whatever you need. In your case, just change the "name" option in the following section to match the path you need.
```
{
    test: /\.(woff2?|ttf|eot|svg|otf)$/,
    loader: 'file-loader',
    options: {
        name: 'fonts/[name].[ext]?[hash]',
        publicPath: Mix.resourceRoot
    }
},
```
so instead of ```name: 'fonts/[name].[ext]?[hash]'``` make it ```name: 'assets/fonts/[name].[ext]?[hash]' ```
just be sure that you remove the --config option from the end of the scripts in your package.json file, in order for your custom config to be referenced.

**Comment by pavinthan** [comment]
Please make it configurable

**Comment by devcircus** [comment]
Every loader and rule is configurable via the config file. When you run "npm run", the webpack.config.js is what is used.
