### ISSUE TITLE
Why is vendor.js also versioned?

### ISSUE THREAD

**Issue by tsunamilx** [JeffreyWay/laravel-mix#573]
- Laravel Mix Version: 0.8.8
- Node Version: 7.2
- NPM Version: 4.1.2
- OS: macOS 10.12.3

### Description:
Using `extract()` and `version()` makes `vendor.js` also versioned.

### Steps To Reproduce:
My script:
```javascript
mix
    .js('resources/assets/js/login.js', 'public/js')
    .js('resources/assets/js/home.js', 'public/js')
    .js('resources/assets/js/followers.js', 'public/js')
    .js('resources/assets/js/groups.js', 'public/js')
    .js('resources/assets/js/qrcodes.js', 'public/js')
    .js('resources/assets/js/followers_analytics.js', 'public/js')
    .extract(['vue', 'vue-material', 'axios'])
    .sass('resources/assets/sass/app.scss', 'public/css')
    .sourceMaps()
    .version()
    .disableNotifications();
```

Result:
![image](https://cloud.githubusercontent.com/assets/6290337/23979560/3c3f7c62-0a35-11e7-9d2f-7ada4a10bbf4.png)

BTW (out of this topic), the latest of mix version is 0.8.8 from npm, but the latest release here is 0.8.2, I am curious how could this happen.

**Comment by devcircus** [comment]
Jeffrey explains this well in this [short video](https://laracasts.com/series/webpack-for-everyone/episodes/11) as part of his webpack series on laracasts. 
I was also curious about the release mismatch between npm and github.

**Comment by tsunamilx** [comment]
@devcircus Great thanks!
@JeffreyWay Any idea about the release mismatch between npm and github?

**Comment by ankurk91** [comment]
Answering to original issue.

Yes, vendor (js/css) should be versioned.  There is no harm in doing that.

For example - your ```vendor.js``` consist of jQuery.js 2.2.4 and bootstrap.js 3.3.7.
And you are serving ```vendor.js``` without cache busting, web browser will cache this file on very first visit.
Later, you bump the jQuery version to 3.1.1 and push the new ```vendor.js``` to server.
But the user will be still using old jQuery because of browser cache. 
Web browser will not serve new vendor.js unless user do a hard refresh on webpage. We can not force user to do that.

If you were using versioning (cache busting) then Laravel-mix will generate a new file name on each of new version of jQuery. This way we could force browser to download and serve new version of our assets.

There can be many more use-case of versioning.

Hope this helps.

**Comment by tsunamilx** [comment]
@ankurk91 Yes, I watch the Jeffrey's video and I understand now. Thanks!
