### ISSUE TITLE
extract() doesn't honor order of libs

### ISSUE THREAD

**Issue by allybee** [JeffreyWay/laravel-mix#659]
The `extract()` function doesn't honor the order of the libs array (I'm not sure _how_ it is ordering them).

I have some libraries that depend on others to be loaded prior. For example, many of my libs depend on jQuery so I want that first. I am also using Bootstrap with a few other related plugins, like Bootstrap Datepicker and Bootstrap Select, both of which need to be loaded after Bootstrap.

My `webpack.mix.js` file contains the following:

```js
mix
    .js('resources/assets/js/app.js', 'public/js')
    .extract([
        'jquery',               // 1
        'bootstrap-sass',       // 2
        'bootstrap-datepicker', // 3
        'bootstrap-select',     // 4
        'moment',               // 5
        'vue',                  // 6
    ])
;
```

However, `vendor.js` combined them in the following order:
```js
'moment',               // 5
'jquery',               // 1
'bootstrap-datepicker', // 3
'bootstrap-sass',       // 2
'bootstrap-select',     // 4
'vue',                  // 6
```

---

- Laravel Mix Version: 0.9.2
- Node Version: 7.8.0
- NPM Version: 4.4.4 
- OS: macOS Sierra 10.12.4

**Comment by adiachenko** [comment]
It's expected behavior, webpack just throws specified chunks into bundle, it doesn't do much else unless you tell it so. For example, it is oblivious to the fact that you attach jquery to window object in the browser before loading bootstrap.

Thence you should `autoload` some dependencies like jQuery if you want to use `extract`. This will instruct webpack to inject them when requested rather than when it feels like it. Than everything will work like you expect.

**Comment by allybee** [comment]
Thank you, I reviewed the [autoloading documentation](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/autoloading.md) and was able to utilize it like you suggested.
