### ISSUE TITLE
Turn off mix-manifest override

### ISSUE THREAD

**Issue by Bounoable** [JeffreyWay/laravel-mix#694]
- Laravel Mix Version: 0.10.0 (`npm list --depth=0`)

This is not a bug but a feature that would be nice to see in Mix.
I'm using Mix to process a lot of assets (mostly one sass and one js file per page and some global assets) and when the list of assets gets really long I often comment out the assets I don't need at the moment to speed up the webpack initialization.

The problem is: When I do that, all previously compiled files (from the mix-manifest) are deleted before the new compilation, so I manually have to edit the manifest before running Mix (so that the files I still need are not deleted) and that can get quite annoying.

It would be nice if we could do something like `mix.keepManifest()` to instruct Mix to only replace the entries in the manifest.

**Comment by pahan35** [comment]
There is Stackoverflow topic
[Laravel Mix multiple entry points generates one manifest.js](https://stackoverflow.com/questions/45046696/laravel-mix-multiple-entry-points-generates-one-manifest-js) where is discussed splitting `webpack.mix.js` approach which is more appropriate in this case.

Otherwise, there are some disadvantages:
1.
2.
