### ISSUE TITLE
Postcss support for plain css files

### ISSUE THREAD

**Issue by rogervila** [JeffreyWay/laravel-mix#728]
- Laravel Mix Version: 0.11.2
- Node Version (`node -v`): 6.10.2
- NPM Version (`npm -v`): 4.5.0
- OS: OSX El Capitan

### Description:
I have a css setup similar to [this one](https://github.com/OnsenUI/OnsenUI/tree/master/css-components/src), where a `index.css` file imports other css files that use [css variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables).

I'd need to apply [postcss-import and postcss-cssnext](http://cssnext.io/postcss/) to the `index.css` file.

### Steps To Reproduce:

There is no support for postcss on mix: https://github.com/JeffreyWay/laravel-mix/issues/617

A `mix.css(src,dist)` method could read css files, parsing the `@import` rules and applying the mix options postcss plugins.

**Comment by ted-piotrowski** [comment]
- Laravel Mix Version: 0.11.3
- Node Version (node -v): 7.8.0
- Yarn Version (): 0.21.3
- OS: OSX El Capitan

I am currently migrating from Laravel Elixir to Mix

I believe I am also running into this issue. PostCSS can only be used with Sass or Less. When this is the case, I believe Sass/Less transformer runs first chocking on PostCSS syntax. In my case, I only have CSS and want to do PostCSS transform, but PostCSS never runs because Sass/Less chokes on the following PostCSS color function syntax

```
  --mixer: color(var(--theme-dark) lightness(10%) saturation(50%));
```

Using LESS: `error evaluating function `lightness`: color.toHSL is not a function`
Using Sass: `Argument `$color` of `lightness($color)` must be a color`

I believe the order of transformation is: 
Sass/Less Loader > PostCSS loader > CSS loader > Style loader

Is there a way to alter the transformation order to be
PostCSS > Sass/Less > CSS > Style

Cheers!

**Comment by hdl-helsinki** [comment]
@JeffreyWay do you plan to implement this on the next version?

**Comment by sebastiandedeyne** [comment]
Been using cssnext instead of sass for some projects lately and would really like to see support for this!

As is, using postcss on it's own in mix was pretty tricky so we had to create a separate npm script for our css processing.

**Comment by allangrds** [comment]
I'm using CSSNext in other projects. It will really nice if Laravel Mix support CSS with Postcss.
