### ISSUE TITLE
laravel mix function has no secure option

### ISSUE THREAD

**Issue by kasperpeulen** [JeffreyWay/laravel-mix#744]
So I use this mix function:

```
    <script src="{{ mix('js/app.js') }}"></script>
```

But it always points to http://localhost:8080/js/app.js. But I'm using `valet secure` in combination with the following npm hot command:
```
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js 
--inline --open --hot --https 
--cert=/Users/Kasper/.localhost-ssl/cert.pem --key=/Users/Kasper/.localhost-ssl/key.pem 
--config=node_modules/laravel-mix/setup/webpack.config.js"
```

The http url seems to be hardcoded:
```
        if (file_exists(public_path($manifestDirectory.'/hot'))) {
            return new HtmlString("http://localhost:8080{$path}");
        }
```

Maybe add an secure option?

**Comment by OwenMelbz** [comment]
Just hit the same issue this morning

**Comment by OwenMelbz** [comment]
After more investigation, with the hope to add a simple PR, the problem seems much deeper.

As you said @kasperpeulen theres lots of hardcoded things that make it unusable in many circumstances.

For example on OSX theres port range restrictions for non-sudo. Meaning that users who have got port 8080 forward to 80 to be able to serve websites without sudo access cant use it either.

So issues I've spotted are

Laravel itself has some issues in `laravel/framework/src/Illuminate/Foundation/helpers.php` as it hardcodes `http://localhost:8080` - which isnt ssl - this could be resolved by something like

```php
if (file_exists(public_path($manifestDirectory.'/hot'))) {
            $hotProtocol = request()->secure() ? 'https' : 'http';
            return new HtmlString("{$hotProtocol}://localhost:8080{$path}");
}
```

Which I've submitted a PR for https://github.com/laravel/framework/pull/18943

To enable SSL on HMR without using a fluent method you can do

```js
mix.webpackConfig({
    devServer: {
        https: true,
        port: 9999
    }
});
```

However the laravel helper does not respect the properties defined here - I think the `mix-manifest.json` or the `public/hot` file should contain the `devServer` config in it, so the mix helper can pull out the port and include that in your application.

@JeffreyWay does this seem like a possibility?

**Comment by OwenMelbz** [comment]
Another update

Just noticed 6 days ago there were some https bits added https://github.com/JeffreyWay/laravel-mix/commit/c74d71d1832946dbb5386dcf266378d9ab97e299

**Comment by kasperpeulen** [comment]
I think your PR would do the trick, I override the mix helper function, like you suggested, and now everything works here. Thanks @OwenMelbz

**Comment by JeffreyWay** [comment]
Looks like that mix PR got merged. Thanks so much.
