### ISSUE TITLE
Npm run dev not registering changes

### ISSUE THREAD

**Issue by lukaisailovic** [JeffreyWay/laravel-mix#806]
I've created new vue component and for some reason it's not registering. It's weird because I already got like 5-6 components working just fine and I can use them but whenever I try to register this new one it's useless. 

Just checked , its not only new components, Its not registering change to any of them including app.js for some reason

**Comment by nscherneck** [comment]
Having the same issue.  I'm on Ubuntu 16.04 using Vagrant/Homestead for local environment.  Can you post your `resources/assets/js/app.js` and `resources/assets/js/bootstrap.js`and the new component?

**Comment by JeffreyWay** [comment]
I'd need you to fill out the issue template to help.

**Comment by ruchern** [comment]
@lukaisailovic Could your application be cached? Clearing the cache or opening `app.js` to manually refresh might solve the problem

**Comment by obb12** [comment]
happens here too

**Comment by obb12** [comment]
Just npm run prod
Then npm run dev

Lähetetty Huawei-matkapuhelimestani

-------- Alkuperäinen viesti --------
Aihe: Re: [JeffreyWay/laravel-mix] Npm run dev not registering changes (#806)
Lähettäjä: Mubashir Abbas
Vastaanottaja: JeffreyWay/laravel-mix
Kopio: Omar Benchbana ,Comment


I am having the same problem.. No change is being recongnized. It was working and suddenly it stopped. I removed everything from app.js and it still shows the same app. changing the file does trigger the watcher to rebuild but it keeps on building an older state of code.

Even if I deliberately make an error, it compiles successfully because it is not compiling my current code.
