### ISSUE TITLE
copyDirectory on npm run watch not working properly

### ISSUE THREAD

**Issue by rezariantono** [JeffreyWay/laravel-mix#883]
Hi

I've noticed _copyDirectory_ on _npm run watch_ is not working properly **when copying for changes**. However, when run for the first time, it runs normally

This is my webpack.mix.js configuration 

`mix.copyDirectory('Test/Test1', 'public/test');`

Copied folder structure as npm run watch is run for the first time (everything is ok)

![image](https://user-images.githubusercontent.com/7689944/27192076-33523144-5224-11e7-8d0e-75fe4210b29e.png)

Copied folder structure as i change the content of test.x file. Notice now the structure from the base path to the directory being watched is also copied

![image](https://user-images.githubusercontent.com/7689944/27192193-9819cd62-5224-11e7-8d9d-a8eb01707b0c.png)

**Comment by ruchern** [comment]
`mix.copyDirectory()` is supposed to work like this and also during `npm run watch`

If you do not want it to keep copying and increase the depth of your directory, you will have to run something like `clean-webpack-plugin` to clean up `test/` directory then re-copying the directory again because of `npm run watch`.

**Comment by JeffreyWay** [comment]
Fixed in 1.0.
