### ISSUE TITLE
JS code bundles are outputted to different folder than the one where the main app.js is outputted 

### ISSUE THREAD

**Issue by silvioiannone** [JeffreyWay/laravel-mix#902]
- Laravel Mix Version: 1.0.0
- Node 7.1.5
- NPM 5.03
- OS: macOS Sierra 10.12.5

### Description:

JS code bundles are outputted to the **public** folder while the main **app.js** file is outputted to **public/js**.

### Steps To Reproduce:

It's enough to run

    npm run dev

**Comment by fragkp** [comment]
I had a similar issue. I had to change from:
`.setPublicPath('public/')`
to:
`setPublicPath('public')`

**Comment by MandaDS** [comment]
I'd like to contribute additional info to this issue since I'm experiencing the same thing and can't figure out a solution. I'm working with a stand-alone project.

- Laravel Mix Version: 1.0.0
- Node 7.8.0
- NPM 4.4.4
- OS: macOS Sierra 10.12.4

My mix file includes the following:

```
    mix.setPublicPath('assets')
        .setResourceRoot('./')
 	.js('./assets/js/app.js', 'dist/js/app.js')
        .extract([
	    'vue', 
	    'jquery', 
	    'tether',
	    'bootstrap'
	]);
```

When I run webpack, the main `app.js` file will appear in `assets/dist/js` folder as expected. However, the chunk/bundle files appear in the main `assets` folder. The `manifest.js` file is directing to load these files from the `assets/dist/js` folder even though they don't exist there:

```
script.src = __webpack_require__.p + "" + ({"20":"/dist/app","21":"/dist/vendor"}[chunkId]||chunkId) + ".js";
```

I can't figure out a way to override this path set in `manifest.js` or force the chunk/bundle file output into the correct folder. I tried setting output chunkFilename to include a different path, but it simply tacks on to what's set in manifest.

**Comment by silvioiannone** [comment]
I was able to solve this problem with this workaround:

    mix.webpackConfig({
        output: {
            chunkFilename: 'js/[name].js',
        }
    });
